import { ContentStatus } from '@prisma/client'
import { NextResponse } from 'next/server'
import { adminError, conflictError, validationError } from '@/lib/admin/api'
import { writeAuditLog } from '@/lib/admin/audit'
import { authorizeAdminRequest } from '@/lib/auth/require-permission'
import { prisma } from '@/lib/db/prisma'
import { contentUpdateSchema } from '@/lib/validation/admin'

const allowedKeys = new Set(['homepage', 'about', 'contact', 'services'])
export async function GET(_: Request, { params }: { params: Promise<{ key: string }> }) { try { await authorizeAdminRequest('content.manage'); const { key } = await params; if (!allowedKeys.has(key)) return NextResponse.json({ error: { code: 'NOT_FOUND' } }, { status: 404 }); const data = await prisma.contentBlock.findUnique({ where: { key }, include: { revisions: { take: 20, orderBy: { createdAt: 'desc' }, include: { author: { select: { name: true, email: true } } } } } }); return NextResponse.json({ data: data ?? { key, value: {}, status: 'DRAFT', version: 1, revisions: [] } }) } catch (error) { return adminError(error) } }
export async function PATCH(request: Request, { params }: { params: Promise<{ key: string }> }) { try { const actor = await authorizeAdminRequest('content.manage'); const { key } = await params; if (!allowedKeys.has(key)) return NextResponse.json({ error: { code: 'NOT_FOUND' } }, { status: 404 }); const parsed = contentUpdateSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return validationError(parsed.error.flatten().fieldErrors); const existing = await prisma.contentBlock.findUnique({ where: { key }, select: { id: true, version: true } }); if (existing && existing.version !== parsed.data.version) return conflictError(); const nextVersion = existing ? existing.version + 1 : 1; const now = new Date(); const data = await prisma.$transaction(async (tx) => { const block = existing ? await tx.contentBlock.update({ where: { id: existing.id }, data: { value: parsed.data.value as object, status: parsed.data.status, version: nextVersion, publishedAt: parsed.data.status === ContentStatus.PUBLISHED ? now : undefined } }) : await tx.contentBlock.create({ data: { key, value: parsed.data.value as object, status: parsed.data.status, version: nextVersion, publishedAt: parsed.data.status === ContentStatus.PUBLISHED ? now : null } }); await tx.contentRevision.create({ data: { contentBlockId: block.id, version: nextVersion, value: parsed.data.value as object, status: parsed.data.status, authorId: actor.id, publisherId: parsed.data.status === ContentStatus.PUBLISHED ? actor.id : null, publishedAt: parsed.data.status === ContentStatus.PUBLISHED ? now : null } }); return block }); await writeAuditLog({ actorId: actor.id, action: parsed.data.status === ContentStatus.PUBLISHED ? 'CONTENT_PUBLISHED' : 'CONTENT_UPDATED', resourceType: 'ContentBlock', resourceId: data.id, summary: `${key} content saved as ${parsed.data.status}.`, request }); return NextResponse.json({ data, message: parsed.data.status === ContentStatus.PUBLISHED ? 'Content published.' : 'Draft saved.' }) } catch (error) { return adminError(error) } }
