import { expect, test, type Page } from '@playwright/test'

const password = 'DriveLuxury!2026'
async function signIn(page: Page, email: string) { await page.goto('/login?callbackUrl=%2Fadmin'); const form = page.locator('.auth-form').first(); await form.getByLabel('Email address').fill(email); await form.getByLabel('Password', { exact: true }).fill(password); await form.getByRole('button', { name: /^sign in/i }).click(); await expect.poll(async () => /\/admin(?:\?.*)?$/.test(page.url()) || await page.getByRole('button', { name: 'Open customer account menu' }).count() > 0, { timeout: 30_000 }).toBe(true); if (!/\/admin(?:\?.*)?$/.test(page.url())) await page.goto('/admin'); await expect(page).toHaveURL(/\/admin(?:\?.*)?$/, { timeout: 30_000 }) }

test('customer cannot enter the staff application', async ({ page }) => { await page.goto('/login?callbackUrl=%2Fadmin'); const form = page.locator('.auth-form').first(); await form.getByLabel('Email address').fill('customer@deccanwheels.local'); await form.getByLabel('Password', { exact: true }).fill(password); await form.getByRole('button', { name: /^sign in/i }).click(); await expect(page.getByRole('button', { name: 'Open customer account menu' })).toBeVisible({ timeout: 15_000 }); await page.goto('/admin'); await expect(page).toHaveURL(/\/login\?callbackUrl=%2Fadmin/); await expect(page.locator('.admin-shell')).toHaveCount(0) })

test('sales can operate assigned lead queues but cannot manage users', async ({ page }) => { await signIn(page, 'sales@deccanwheels.local'); await page.goto('/admin/enquiries'); await expect(page.getByRole('heading', { name: 'Enquiries' })).toBeVisible(); await expect(page.getByRole('link', { name: 'OA-ENQ-DEMO-000001' }).first()).toBeVisible(); await page.goto('/admin/users'); await expect(page).toHaveURL(/\/admin\?forbidden=user.view/); await expect(page.getByRole('heading', { name: 'Operations Dashboard' })).toBeVisible() })

test('content manager can manage published media but not private sell workflows', async ({ page }) => { await signIn(page, 'content@deccanwheels.local'); await page.goto('/admin/testimonials'); await expect(page.getByRole('heading', { name: 'Testimonials' })).toBeVisible(); await expect(page.getByRole('cell', { name: 'Rohan Mehta' })).toBeVisible(); await page.goto('/admin/sell-requests'); await expect(page).toHaveURL(/\/admin\?forbidden=sellRequest.view/) })

test('admin dashboard and database-backed management pages load', async ({ page }) => { await signIn(page, 'admin@deccanwheels.local'); await expect(page.getByRole('heading', { name: 'Operations Dashboard' })).toBeVisible(); await expect(page.getByText('Available vehicles')).toBeVisible(); await page.goto('/admin/vehicles'); await expect(page.getByRole('heading', { name: 'Vehicle Inventory' })).toBeVisible(); await expect(page.getByRole('cell').filter({ hasText: 'OA-0030' }).first()).toBeVisible(); await page.goto('/admin/showrooms'); await expect(page.getByRole('heading', { name: 'Optimum Automobiles', exact: true })).toBeVisible(); await page.goto('/admin/audit-logs'); await expect(page.getByRole('heading', { name: 'Audit Logs' })).toBeVisible() })

test('admin lead detail has assignment, private notes and workflow controls', async ({ page }) => { await signIn(page, 'admin@deccanwheels.local'); await page.goto('/admin/enquiries'); const href = await page.getByRole('link', { name: 'OA-ENQ-DEMO-000001' }).first().getAttribute('href'); expect(href).toBeTruthy(); await page.goto(href!); await expect(page.getByRole('heading', { name: /OA-ENQ-DEMO-000001/ })).toBeVisible(); await expect(page.getByRole('heading', { name: 'Assignment' })).toBeVisible(); await expect(page.getByRole('heading', { name: 'Conversation and notes' })).toBeVisible(); await expect(page.getByRole('heading', { name: 'Activity timeline' })).toBeVisible() })

test('public contact submission becomes an admin contact record', async ({ page }) => { const unique = `Browser Admin ${Date.now()}`; await page.goto('/contact'); const form = page.locator('.contact-page-form'); await form.getByLabel('Full Name *').fill(unique); await form.getByLabel('Phone Number *').fill('9876543210'); await form.getByLabel('Email Address *').fill(`admin-browser-${Date.now()}@example.com`); await form.getByLabel('Subject *').selectOption({ label: 'Buying a car' }); await form.getByLabel('Message *').fill('Please ask your sales team to contact me about an available sedan.'); await form.getByRole('button', { name: /send message/i }).click(); await expect(form.locator('[role="status"]')).toContainText('Reference:', { timeout: 30_000 }); await signIn(page, 'admin@deccanwheels.local'); await page.goto('/admin/contact-inquiries'); await expect(page.getByRole('cell', { name: unique })).toBeVisible({ timeout: 15_000 }) })

test('mobile admin routes have no horizontal document overflow', async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); await signIn(page, 'admin@deccanwheels.local'); for (const route of ['/admin', '/admin/vehicles', '/admin/enquiries', '/admin/users']) { await page.goto(route); expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), route).toBe(false) } })
