'use client'

import { BadgeCheck, Car, ClipboardCheck, FileCheck2, Handshake, Headphones, Search, ShieldCheck } from 'lucide-react'
import { FaqList, IconFeatureGrid, InteriorCta, InteriorHeading, PageHero, ProcessSteps } from './PagePrimitives'
import { interiorImages } from '@/lib/constants/interior'

type PageContent = {
  eyebrow: string
  title: string
  accent?: string
  intro: string
  sectionTitle: string
  paragraphs: string[]
  points: Array<{ title: string; text: string }>
  faqs?: string[][]
}

const icons = [ShieldCheck, FileCheck2, Handshake, Headphones]

const pageContent: Record<string, PageContent> = {
  finance: { eyebrow: 'Services / Finance', title: 'Flexible Car Finance,', accent: 'Clearly Explained.', intro: 'Explore funding options for your chosen pre-owned car with documentation support from application to disbursal.', sectionTitle: 'Finance support built around your purchase', paragraphs: ['Finance approval, interest rate, tenure and loan-to-value are decided by the lending partner after reviewing your eligibility and the vehicle. We help prepare the application and compare available offers; we do not promise approval.', 'Before you sign, review the lender sanction letter, processing fees, foreclosure rules, insurance requirements and total repayment amount.'], points: [{ title: 'Eligibility guidance', text: 'A clear checklist for income, identity and address documents.' }, { title: 'Lender coordination', text: 'Application support with participating banks and finance partners.' }, { title: 'Transparent comparison', text: 'Compare rate, tenure, fees and total repayment—not only the EMI.' }, { title: 'Delivery coordination', text: 'Purchase paperwork and disbursal are aligned before handover.' }], faqs: [['Can you guarantee a loan approval?', 'No. Approval and final terms are solely at the lender’s discretion.'], ['What documents are normally required?', 'Identity, address and income documents are usually required; the exact list varies by applicant and lender.'], ['Can I make a larger down payment?', 'Yes, subject to the lender’s minimum and maximum funding rules.']] },
  insurance: { eyebrow: 'Services / Insurance', title: 'Insurance Assistance', accent: 'Without the Guesswork.', intro: 'Understand coverage options and coordinate policy issuance or transfer for your vehicle.', sectionTitle: 'Coverage that matches the car and owner', paragraphs: ['We can help collect quotations and explain common cover choices, deductibles and add-ons. The insurer issues the policy and makes all underwriting and claim decisions.', 'Always verify the insured declared value, named owner, registration details, add-ons, exclusions and claim process before payment.'], points: [{ title: 'Quote coordination', text: 'Request comparable quotations from participating insurers.' }, { title: 'Policy checks', text: 'Review owner, vehicle, IDV and coverage details before issuance.' }, { title: 'Transfer support', text: 'Coordinate the policy transfer required after a pre-owned purchase.' }, { title: 'Claim guidance', text: 'Help locate insurer contacts and required claim documents.' }] },
  warranty: { eyebrow: 'Services / Extended Warranty', title: 'Extended Warranty', accent: 'For Added Confidence.', intro: 'Ask about eligible third-party protection plans for selected pre-owned cars.', sectionTitle: 'Know exactly what the plan covers', paragraphs: ['Availability depends on vehicle age, mileage, inspection results and the plan provider. Coverage is not automatic and should never be treated as equivalent to a new-car manufacturer warranty.', 'We provide the applicable plan document so you can review covered components, exclusions, waiting periods, claim limits and approved repair process before opting in.'], points: [{ title: 'Eligibility check', text: 'Confirm whether the specific vehicle qualifies for a plan.' }, { title: 'Written coverage', text: 'Review covered parts and exclusions in the provider document.' }, { title: 'Claim process', text: 'Understand authorisation requirements before repairs begin.' }, { title: 'Optional purchase', text: 'The plan is optional and separately priced when available.' }] },
  transfer: { eyebrow: 'Services / RC Transfer', title: 'Ownership Transfer,', accent: 'Handled Carefully.', intro: 'Structured document support for transferring the registration certificate after a sale.', sectionTitle: 'A documented handover process', paragraphs: ['We coordinate the forms and supporting documents typically required for an ownership transfer. Timelines depend on the relevant RTO, document completeness, hypothecation status and interstate requirements.', 'Customers receive updates and should retain copies of signed documents and transaction records until the updated registration certificate is issued.'], points: [{ title: 'Document checklist', text: 'Identify the forms, KYC, insurance and registration documents required.' }, { title: 'Application support', text: 'Coordinate submission with the relevant transport authority or facilitator.' }, { title: 'Status follow-up', text: 'Track known milestones and request missing information promptly.' }, { title: 'Record retention', text: 'Keep a clear transaction trail through completion.' }] },
  process: { eyebrow: 'Information / Our Process', title: 'A Clear Journey,', accent: 'From Search to Handover.', intro: 'Every purchase follows a consistent sequence so you know what happens next.', sectionTitle: 'How buying a car works', paragraphs: ['Start by browsing current inventory and asking for the inspection and ownership information available for the car. After a viewing and test drive, we document the agreed vehicle, price and included services.', 'Payment, finance, insurance and transfer paperwork are verified before the physical handover. Keep all receipts and signed documents for your records.'], points: [{ title: 'Discover', text: 'Shortlist current cars that fit your budget and ownership needs.' }, { title: 'Inspect and drive', text: 'Review the car, available records and test-drive it safely.' }, { title: 'Agree in writing', text: 'Confirm the price, inclusions, payment milestones and conditions.' }, { title: 'Complete and collect', text: 'Verify paperwork and handover items before taking delivery.' }] },
  why: { eyebrow: 'Information / Why Choose Us', title: 'Premium Service,', accent: 'Grounded in Clarity.', intro: 'A focused pre-owned car experience built around documented information and responsive support.', sectionTitle: 'The Optimum approach', paragraphs: ['We aim to present each available car accurately, explain the transaction clearly and coordinate the practical steps around purchase or sale.', 'No used vehicle is risk-free. We encourage customers to inspect, test-drive, ask questions and read every document before committing.'], points: [{ title: 'Curated inventory', text: 'A focused selection rather than an unverified marketplace feed.' }, { title: 'Inspection-led', text: 'Available condition information is shared for informed decisions.' }, { title: 'Clear transaction', text: 'Pricing, inclusions and next steps are documented.' }, { title: 'Ownership support', text: 'Assistance with finance, insurance and transfer coordination.' }] },
  reviews: { eyebrow: 'Information / Testimonials', title: 'Customer Feedback', accent: 'We Can Stand Behind.', intro: 'Published feedback is moderated and clearly labelled; verified-buyer status is shown only when supported by a completed transaction.', sectionTitle: 'Real feedback, responsibly presented', paragraphs: ['We do not treat sample content as verified customer testimony. Reviews published through the admin system can be checked against a completed purchase or sale before receiving a verified label.', 'Want to share your experience? Contact the showroom with your transaction reference and feedback.'], points: [{ title: 'Moderated', text: 'Submissions are reviewed for relevance and personal information.' }, { title: 'Verification labelled', text: 'A badge is used only when a matching transaction can be confirmed.' }, { title: 'Balanced feedback', text: 'Constructive feedback helps improve the ownership experience.' }, { title: 'Privacy aware', text: 'Only approved display names and details are published.' }] },
  blog: { eyebrow: 'Information / Guides', title: 'Car Buying', accent: 'Guides & Updates.', intro: 'Practical guidance for evaluating, buying, financing and owning a premium pre-owned car.', sectionTitle: 'Useful topics from the showroom', paragraphs: ['Our guide library is being prepared with reviewed, date-stamped articles. Until publication, our team can explain inspection records, ownership costs, finance comparisons and transfer steps for a specific vehicle.', 'Advice on this site is general information. Finance, insurance, tax and legal decisions should be checked with the relevant qualified provider.'], points: [{ title: 'Buying checklist', text: 'Questions to ask before you reserve a pre-owned vehicle.' }, { title: 'Ownership costs', text: 'Think beyond price: insurance, service, tyres and running costs.' }, { title: 'Finance basics', text: 'Compare total repayment, fees and flexibility across offers.' }, { title: 'Document checks', text: 'Review RC, insurance and transfer records carefully.' }] },
}

export function CompletePage({ pageKey }: { pageKey: string }) {
  const content = pageContent[pageKey]
  return <main className="interior-page" id="main-content"><PageHero eyebrow={content.eyebrow} title={content.title} accent={content.accent} text={content.intro} image={interiorImages.hero} /><section className="story-section container-wide"><div><InteriorHeading title={content.sectionTitle} /><div>{content.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div><div><IconFeatureGrid items={content.points.map((point, index) => ({ ...point, icon: icons[index % icons.length] }))} /></div></section>{content.eyebrow.includes('Our Process') ? <section className="interior-section container-wide"><InteriorHeading title="Four straightforward stages" /><ProcessSteps items={content.points.map((point, index) => ({ ...point, icon: [Search, ClipboardCheck, BadgeCheck, Car][index] }))} /></section> : null}{content.faqs ? <section className="interior-section container-wide"><InteriorHeading title="Frequently Asked Questions" /><FaqList items={content.faqs} /></section> : null}<InteriorCta title="Talk to Our Showroom Team" text="Ask about a specific car or service and receive clear next steps." image={interiorImages.sedan} primary={{ label: 'Contact Us', href: '/contact' }} secondary={{ label: 'Browse Inventory', href: '/inventory' }} /></main>
}

export function LegalPage({ title, updated, children }: { title: string; updated: string; children: React.ReactNode }) {
  return <main className="interior-page legal-page" id="main-content"><PageHero eyebrow="Legal" title={title} text={`Last updated ${updated}`} image={interiorImages.hero} /><article className="container-narrow placeholder-panel legal-copy">{children}</article></main>
}
