import { NextResponse } from 'next/server'
import { adminError, validationError } from '@/lib/admin/api'
import { writeAuditLog } from '@/lib/admin/audit'
import { authorizeAdminRequest } from '@/lib/auth/require-permission'
import { createOneTimeToken, expiresInMinutes } from '@/lib/auth/tokens'
import { prisma } from '@/lib/db/prisma'
import { sendStaffInvitationEmail } from '@/lib/email/service'
import { staffInviteSchema } from '@/lib/validation/admin'

export async function GET(request: Request) { try { await authorizeAdminRequest('user.view'); const query = new URL(request.url).searchParams; const search = query.get('search')?.trim(); const data = await prisma.user.findMany({ where: { deletedAt: null, ...(search ? { OR: [{ name: { contains: search, mode: 'insensitive' } }, { email: { contains: search, mode: 'insensitive' } }] } : {}) }, orderBy: [{ role: 'asc' }, { name: 'asc' }], include: { _count: { select: { sessions: true } } } }); return NextResponse.json({ data: data.map(({ passwordHash: _, ...user }) => user) }) } catch (error) { return adminError(error) } }
export async function POST(request: Request) { try { const actor = await authorizeAdminRequest('user.invite'); const parsed = staffInviteSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return validationError(parsed.error.flatten().fieldErrors); const existing = await prisma.user.findUnique({ where: { email: parsed.data.email } }); if (existing) return NextResponse.json({ error: { code: 'ACCOUNT_EXISTS', message: 'An account already uses this email.' } }, { status: 409 }); const { token, tokenHash } = createOneTimeToken(); const invitation = await prisma.staffInvitation.create({ data: { email: parsed.data.email, role: parsed.data.role, tokenHash, invitedById: actor.id, expiresAt: expiresInMinutes(48 * 60) } }); let preview = false; try { preview = (await sendStaffInvitationEmail(invitation.email, token, invitation.role)).preview } catch (emailError) { console.error('staff_invitation_email_failed', { invitationId: invitation.id, emailError }) } await writeAuditLog({ actorId: actor.id, action: 'STAFF_INVITED', resourceType: 'StaffInvitation', resourceId: invitation.id, summary: `Invited ${invitation.email} as ${invitation.role}.`, request }); const previewVisible = process.env.NODE_ENV !== 'production' || process.env.ALLOW_EMAIL_PREVIEW === 'true'; return NextResponse.json({ data: { id: invitation.id, email: invitation.email, expiresAt: invitation.expiresAt, ...(preview && previewVisible ? { previewUrl: `/staff-invitation?token=${encodeURIComponent(token)}` } : {}) }, message: 'Staff invitation created.' }, { status: 201 }) } catch (error) { return adminError(error) } }
