'use client'

import { LoaderCircle, Plus, Save } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { useState, type FormEvent } from 'react'
import { AdminStatus } from './AdminPrimitives'

type Item = { id: string; name: string; slug: string; description: string | null; active: boolean; category?: string; logoUrl?: string; logoAlt?: string; websiteUrl?: string | null; country?: string; icon?: string | null; imageUrl?: string | null; featured?: boolean; displayOrder?: number; _count: { vehicles: number } }
export function CatalogManager({ resource, items }: { resource: 'brands' | 'body-types' | 'features'; items: Item[] }) {
  const router = useRouter(); const [editing, setEditing] = useState<Item | null>(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage(''); const form = Object.fromEntries(new FormData(event.currentTarget)); const payload = { ...form, active: form.active === 'on', featured: form.featured === 'on', displayOrder: Number(form.displayOrder ?? 0), ...(resource === 'brands' ? { logoUrl: form.logoUrl || '/images/brand-logos/default.svg', logoAlt: form.logoAlt || `${form.name} logo`, country: form.country || 'Unknown' } : {}), ...(resource === 'features' ? { category: form.category || 'COMFORT' } : {}) }
    const response = await fetch(`/api/admin/catalog/${resource}${editing ? `/${editing.id}` : ''}`, { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const body = await response.json(); setBusy(false); setMessage(body.message ?? body.error?.message ?? 'Operation failed.'); if (response.ok) { setEditing(null); event.currentTarget.reset(); router.refresh() }
  }
  return <div className="admin-detail-layout"><div><div className="admin-table-wrap"><table className="admin-table"><caption>{items.length} catalog records</caption><thead><tr><th>Name</th><th>Slug</th>{resource === 'features' ? <th>Category</th> : null}<th>Vehicles</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.slug}</td>{resource === 'features' ? <td>{item.category}</td> : null}<td>{item._count.vehicles}</td><td><AdminStatus value={item.active ? 'Active' : 'Inactive'} /></td><td><button className="admin-button admin-button--secondary" type="button" onClick={() => setEditing(item)}>Edit</button></td></tr>)}</tbody></table></div><div className="admin-mobile-cards">{items.map((item) => <article className="admin-mobile-card" key={item.id}><header><h2>{item.name}</h2><AdminStatus value={item.active ? 'Active' : 'Inactive'} /></header><p>{item.slug} · {item._count.vehicles} vehicles</p><footer><span>{item.category}</span><button className="admin-button admin-button--secondary" type="button" onClick={() => setEditing(item)}>Edit</button></footer></article>)}</div></div>
    <aside className="admin-panel"><header><h2>{editing ? `Edit ${editing.name}` : `Add ${resource.replace('-', ' ')}`}</h2></header><div className="admin-panel__body"><form className="admin-form" onSubmit={submit}><label>Name<input name="name" required defaultValue={editing?.name} /></label><label>Slug<input name="slug" required defaultValue={editing?.slug} /></label><label>Description<textarea name="description" defaultValue={editing?.description ?? ''} /></label>{resource === 'brands' ? <><label>Logo URL<input name="logoUrl" defaultValue={editing?.logoUrl} /></label><label>Logo alt text<input name="logoAlt" defaultValue={editing?.logoAlt} /></label><label>Website<input name="websiteUrl" defaultValue={editing?.websiteUrl ?? ''} /></label><label>Country<input name="country" defaultValue={editing?.country} /></label></> : null}{resource === 'body-types' ? <><label>Icon<input name="icon" defaultValue={editing?.icon ?? ''} /></label><label>Image URL<input name="imageUrl" defaultValue={editing?.imageUrl ?? ''} /></label></> : null}{resource === 'features' ? <label>Category<select name="category" defaultValue={editing?.category ?? 'COMFORT'}>{['SAFETY','COMFORT','INFOTAINMENT','EXTERIOR','INTERIOR','PERFORMANCE','CONVENIENCE'].map((value) => <option key={value}>{value}</option>)}</select></label> : <label>Display order<input name="displayOrder" type="number" defaultValue={editing?.displayOrder ?? 0} /></label>}<label className="admin-checkbox"><input name="active" type="checkbox" defaultChecked={editing?.active ?? true} /><span>Active</span></label>{resource !== 'features' ? <label className="admin-checkbox"><input name="featured" type="checkbox" defaultChecked={editing?.featured ?? false} /><span>Featured</span></label> : null}{message ? <p className="admin-form-message" role="status">{message}</p> : null}<button className="admin-button" disabled={busy}>{busy ? <LoaderCircle /> : editing ? <Save /> : <Plus />}{editing ? 'Save changes' : 'Create record'}</button>{editing ? <button className="admin-button admin-button--secondary" type="button" onClick={() => setEditing(null)}>Cancel</button> : null}</form></div></aside>
  </div>
}
