import { notFound } from 'next/navigation'
import { AdminPageHeader, AdminStatus } from './AdminPrimitives'
import { LeadActions } from './LeadActions'
import { leadResource, listStaff, requireAccessibleLead, type LeadKind } from '@/lib/admin/lead-service'
import type { AdminPermission } from '@/lib/auth/admin-permissions'
import { requirePermission } from '@/lib/auth/require-permission'
import { prisma } from '@/lib/db/prisma'
import { mayViewPrivateDocuments } from '@/lib/auth/admin-resource-policy'

function text(value: unknown) { return value === null || value === undefined || value === '' ? 'Not provided' : String(value) }
export async function LeadDetailPage({ kind, id, title, permission }: { kind: LeadKind; id: string; title: string; permission: AdminPermission }) {
  const actor = await requirePermission(permission); const lead = await requireAccessibleLead(kind, id, actor); if (!lead) notFound()
  const [staff, messages, activity, attachments] = await Promise.all([listStaff(), prisma.operationalMessage.findMany({ where: { resourceType: leadResource[kind], resourceId: id }, orderBy: { createdAt: 'asc' }, include: { author: { select: { name: true } } } }), prisma.operationalActivity.findMany({ where: { resourceType: leadResource[kind], resourceId: id }, orderBy: { createdAt: 'desc' }, include: { actor: { select: { name: true } } } }), kind === 'sell-requests' && mayViewPrivateDocuments(actor.role) ? prisma.sellRequestAttachment.findMany({ where: { sellRequestId: id }, orderBy: { createdAt: 'asc' } }) : []])
  const record = lead as typeof lead & { referenceNumber: string; status: string; priority: string; version: number; assignedToId: string | null; phone?: string | null; email?: string | null; message?: string | null; fullName?: string; name?: string | null; make?: string | null; model?: string | null; year?: number | null; city?: string | null; subject?: string | null; preferredDate?: Date; preferredTime?: string; confirmedDate?: Date | null; confirmedTime?: string | null }
  const name = record.fullName ?? record.name ?? 'Customer'; const subject = kind === 'sell-requests' ? [record.year, record.make, record.model].filter(Boolean).join(' ') : kind === 'contact-inquiries' ? record.subject : 'vehicle' in record ? record.vehicle?.shortTitle : ''
  return <><AdminPageHeader title={`${title} ${record.referenceNumber}`} text="Assignment-aware staff workspace with private notes, customer communication and an append-only activity trail." breadcrumb={`${title} / ${record.referenceNumber}`} actions={<AdminStatus value={record.status} />} /><div className="admin-detail-layout"><div className="admin-detail-stack"><section className="admin-panel admin-panel--full"><header><h2>Customer and request</h2></header><div className="admin-kv"><div><small>Customer</small><strong>{name}</strong></div><div><small>Priority</small><strong>{record.priority}</strong></div><div><small>Phone</small><strong>{text(record.phone)}</strong></div><div><small>Email</small><strong>{text(record.email)}</strong></div><div><small>Vehicle / subject</small><strong>{text(subject)}</strong></div><div><small>Location</small><strong>{text(record.city)}</strong></div>{kind === 'test-drives' ? <><div><small>Preferred</small><strong>{record.preferredDate?.toLocaleDateString('en-IN')} {record.preferredTime}</strong></div><div><small>Confirmed</small><strong>{record.confirmedDate?.toLocaleDateString('en-IN') ?? 'Pending'} {record.confirmedTime}</strong></div></> : null}</div><div className="admin-panel__body"><small>Original message</small><p>{text(record.message)}</p></div></section>{kind === 'sell-requests' && mayViewPrivateDocuments(actor.role) ? <section className="admin-panel admin-panel--full"><header><h2>Private attachments</h2></header><div className="admin-panel__body">{attachments.length ? <ul>{attachments.map((item) => <li key={item.id}><a href={`/api/admin/sell-requests/${id}/attachments/${item.id}`}>{item.originalName}</a> <small>({(item.sizeBytes / 1024 / 1024).toFixed(1)} MB)</small></li>)}</ul> : <p>No files were attached.</p>}</div></section> : null}<section className="admin-panel admin-panel--full"><header><h2>Messages</h2></header><div className="admin-panel__body admin-timeline">{messages.length ? messages.map((item) => <article key={item.id}><strong>{item.customerVisible ? 'Customer update' : 'Internal note'} by {item.author?.name ?? 'System'}</strong><p>{item.body}</p><time>{item.createdAt.toLocaleString('en-IN')}</time></article>) : <p>No messages recorded.</p>}</div></section><section className="admin-panel admin-panel--full"><header><h2>Activity timeline</h2></header><div className="admin-panel__body admin-timeline">{activity.map((item) => <article key={item.id}><strong>{item.action.replaceAll('_', ' ')}</strong><p>{item.summary}</p><time>{item.actor?.name ?? 'System'} - {item.createdAt.toLocaleString('en-IN')}</time></article>)}</div></section></div><LeadActions kind={kind} id={id} status={record.status} version={record.version} assignedToId={record.assignedToId} staff={staff.map((person) => ({ ...person, name: person.name ?? person.email }))} /></div></>
}
