'use client'

import { LoaderCircle, MessageSquareText, Save, Send } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { useState, type FormEvent } from 'react'
import type { LeadKind } from '@/lib/admin/lead-service'

const statuses: Record<LeadKind, string[]> = {
  enquiries: ['NEW', 'ASSIGNED', 'CONTACTED', 'IN_PROGRESS', 'WAITING_FOR_CUSTOMER', 'RESOLVED', 'CLOSED', 'CANCELLED', 'SPAM'],
  'test-drives': ['REQUESTED', 'CONFIRMED', 'RESCHEDULE_REQUESTED', 'RESCHEDULED', 'COMPLETED', 'CANCELLED', 'REJECTED', 'NO_SHOW'],
  'sell-requests': ['SUBMITTED', 'UNDER_REVIEW', 'CONTACTED', 'INSPECTION_SCHEDULED', 'INSPECTION_COMPLETED', 'VALUATION_READY', 'OFFER_MADE', 'NEGOTIATING', 'OFFER_ACCEPTED', 'OFFER_REJECTED', 'DOCUMENTATION', 'PAYMENT_PROCESSING', 'COMPLETED', 'CANCELLED'],
  'contact-inquiries': ['NEW', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_FOR_CUSTOMER', 'RESOLVED', 'CLOSED', 'DUPLICATE', 'SPAM'],
}

type Staff = { id: string; name: string; role: string }
export function LeadActions({ kind, id, status, version, assignedToId, staff }: { kind: LeadKind; id: string; status: string; version: number; assignedToId: string | null; staff: Staff[] }) {
  const router = useRouter(); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  async function call(url: string, body: unknown) { setBusy(true); setMessage(''); const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json(); setBusy(false); setMessage(payload.message ?? payload.error?.message ?? 'Action failed.'); if (response.ok) router.refresh() }
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget)); setBusy(true); const response = await fetch(`/api/admin/${kind}/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: form.status, priority: form.priority, followUpAt: form.followUpAt || null, version }) }); const payload = await response.json(); setBusy(false); setMessage(payload.message ?? payload.error?.message ?? 'Update failed.'); if (response.ok) router.refresh() }
  async function note(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); await call(`/api/admin/${kind}/${id}/${values.customerVisible === 'on' ? 'message' : 'note'}`, { body: values.body, customerVisible: values.customerVisible === 'on', type: values.customerVisible === 'on' ? 'CUSTOMER_MESSAGE' : 'INTERNAL_NOTE' }); form.reset() }
  return <div className="admin-detail-stack"><section className="admin-panel admin-panel--full"><header><h2>Workflow control</h2></header><div className="admin-panel__body"><form className="admin-form" onSubmit={update}><label>Status<select name="status" defaultValue={status}>{statuses[kind].map((value) => <option key={value}>{value}</option>)}</select></label><label>Priority<select name="priority" defaultValue="NORMAL"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label><label>Follow-up<input name="followUpAt" type="datetime-local" /></label><button className="admin-button" disabled={busy}>{busy ? <LoaderCircle /> : <Save />}Update workflow</button></form></div></section><section className="admin-panel admin-panel--full"><header><h2>Assignment</h2></header><div className="admin-panel__body"><label className="admin-form">Assigned staff<select defaultValue={assignedToId ?? ''} onChange={(event) => call(`/api/admin/${kind}/${id}/assign`, { assigneeId: event.target.value || null, version })}><option value="">Unassigned queue</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.name} - {person.role}</option>)}</select></label></div></section><section className="admin-panel admin-panel--full"><header><h2>Conversation and notes</h2></header><div className="admin-panel__body"><form className="admin-form" onSubmit={note}><label>Message<textarea name="body" required placeholder="Record an internal note or a customer update" /></label><label className="admin-checkbox"><input name="customerVisible" type="checkbox" /><span>Visible to customer</span></label><button className="admin-button" disabled={busy}>{busy ? <LoaderCircle /> : <MessageSquareText />}Add message</button></form></div></section>{kind === 'test-drives' ? <ScheduleForm id={id} version={version} call={call} busy={busy} /> : null}{kind === 'sell-requests' ? <SellForms id={id} call={call} busy={busy} /> : null}{message ? <p className="admin-form-message" role="status">{message}</p> : null}</div>
}

function ScheduleForm({ id, version, call, busy }: { id: string; version: number; call: (url: string, body: unknown) => Promise<void>; busy: boolean }) {
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); await call(`/api/admin/test-drives/${id}/${values.mode}`, { confirmedDate: values.confirmedDate, confirmedTime: values.confirmedTime, note: values.note, version }) }
  return <section className="admin-panel admin-panel--full"><header><h2>Appointment</h2></header><div className="admin-panel__body"><form className="admin-form" onSubmit={submit}><label>Action<select name="mode"><option value="confirm">Confirm</option><option value="reschedule">Reschedule</option></select></label><label>Date<input name="confirmedDate" type="date" required /></label><label>Time<input name="confirmedTime" type="time" required /></label><label>Customer note<input name="note" /></label><button className="admin-button" disabled={busy}><Send />Save appointment</button></form></div></section>
}

function SellForms({ id, call, busy }: { id: string; call: (url: string, body: unknown) => Promise<void>; busy: boolean }) {
  async function inspection(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); await call(`/api/admin/sell-requests/${id}/inspection`, { ...data, documentsVerified: data.documentsVerified === 'on', serviceHistoryVerified: data.serviceHistoryVerified === 'on' }) }
  async function valuation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); await call(`/api/admin/sell-requests/${id}/valuation`, data) }
  return <><section className="admin-panel admin-panel--full"><header><h2>Inspection</h2></header><div className="admin-panel__body"><form className="admin-form" onSubmit={inspection}><label>Scheduled at<input name="scheduledAt" type="datetime-local" /></label><label>Location<input name="location" /></label><label>Exterior score<input name="exteriorScore" type="number" min="1" max="10" /></label><label>Interior score<input name="interiorScore" type="number" min="1" max="10" /></label><label>Mechanical score<input name="mechanicalScore" type="number" min="1" max="10" /></label><label>Overall score<input name="overallConditionScore" type="number" min="1" max="10" /></label><label className="admin-checkbox"><input name="documentsVerified" type="checkbox" /><span>Documents verified</span></label><label className="admin-checkbox"><input name="serviceHistoryVerified" type="checkbox" /><span>Service history verified</span></label><label>Internal notes<textarea name="staffNotes" /></label><label>Customer summary<textarea name="customerSummary" /></label><button className="admin-button" disabled={busy}><Save />Save inspection</button></form></div></section><section className="admin-panel admin-panel--full"><header><h2>Valuation and offer</h2></header><div className="admin-panel__body"><form className="admin-form" onSubmit={valuation}><label>Market minimum<input name="marketMinimum" type="number" required /></label><label>Market maximum<input name="marketMaximum" type="number" required /></label><label>Recommended offer<input name="recommendedOffer" type="number" required /></label><label>Final customer offer<input name="finalOffer" type="number" /></label><label>Valid until<input name="validUntil" type="date" required /></label><label>Internal notes<textarea name="notes" /></label><button className="admin-button" disabled={busy}><Save />Create valuation</button></form></div></section></>
}
